{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mokelab.android",
    "module": "gradle-plugin",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.3.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 14348,
          "sha512": "bd715fbda332f970e065e22771df3919258f672fb272f68b1a72484bea6c0eb876951f90783c675c3b6f4cb3ab95c724b4bad54af145a9dacee5b9c264e4092c",
          "sha256": "0865ae04e5b12d59ef0c3e61505ba9823e14f06b2af304f26496757387847791",
          "sha1": "9c81f17f76fcca6a527517bf12a8e94aa8d24897",
          "md5": "9401a910654058051740bdc731f272c0"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 21,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "gradle-plugin-1.0.0.jar",
          "url": "gradle-plugin-1.0.0.jar",
          "size": 14348,
          "sha512": "bd715fbda332f970e065e22771df3919258f672fb272f68b1a72484bea6c0eb876951f90783c675c3b6f4cb3ab95c724b4bad54af145a9dacee5b9c264e4092c",
          "sha256": "0865ae04e5b12d59ef0c3e61505ba9823e14f06b2af304f26496757387847791",
          "sha1": "9c81f17f76fcca6a527517bf12a8e94aa8d24897",
          "md5": "9401a910654058051740bdc731f272c0"
        }
      ]
    }
  ]
}
